---
# This is the TorqueBox configuration file. Refer to the TorqueBox
# documentation at http://torquebox.org/documentation/current/ 
# for all configuration options.
web:
  context: "/"
# jobs:
# heart_beat:
#   job: HeartBeat
#   cron: "*/15 * * * * ?"
